[paths]
    opt = "/opt"
    usrlocal = "/usr/local"

[paths.local]
    bin   = ".local/bin"
    lib   = ".local/lib"
    etc   = ".local/etc"
    cargo = ".cargo/bin"
    lldb  = ".local/share/mea-lldb"

[paths.apple]
    appsupport = "Library/Application Support"
    app = "/Applications"
