[tools]
erlang = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
elixir = "latest"
java = "latest"
swift = "latest"
pipx = "latest"
npm = "latest"
ruby = "latest"
"npm:hookdeck-cli" = "latest"
"npm:ghost-cli" = "latest"
"npm:typescript" = "latest"
"cargo:cargo-bump" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
ignored_config_paths = [
  "{{ .chezmoi.homeDir }}/.local/config/share/chezmoi/dot_config/mise",
]
experimental = true
